import { ArrowRight, BriefcaseBusiness, Check, Mail } from "lucide-react";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import PageHero from "@/components/ui/PageHero";
import { Button } from "@/components/ui/Button";
import { careerMessage, careerProfiles } from "@/data/careers";

export const metadata = { title: "Carrière", description: "Rejoindre YEHI OR Tech et contribuer à des solutions numériques utiles en Afrique francophone." };

export default function CareersPage() { return <main className="min-h-screen bg-white"><Navbar/><PageHero eyebrow="Rejoindre l’équipe" title="Construire des solutions qui éclairent vraiment." description="Nous cherchons des profils curieux, exigeants et orientés impact pour accompagner la transformation numérique des organisations." image="/images/heroes/about.png" cta="Proposer ma candidature"/><section className="site-container section-padding grid gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Notre culture</p><h2 className="mt-5 text-noir-profond">Une petite équipe, des problèmes qui comptent.</h2><p className="mt-6 text-lg leading-8 text-gris">{careerMessage}</p><div className="mt-8 rounded-3xl bg-bleu-soft p-6 text-sm leading-7 text-noir-profond"><Check className="h-5 w-5 text-or"/><p className="mt-3">Clarté dans les échanges, autonomie dans l’exécution et apprentissage continu.</p></div></div><div><p className="eyebrow">Profils recherchés</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{careerProfiles.map(profile=><div key={profile} className="flex items-center gap-3 rounded-2xl border border-slate-200 p-5"><BriefcaseBusiness className="h-5 w-5 text-bleu-tech"/><span className="text-sm font-semibold text-noir-profond">{profile}</span></div>)}</div><div className="mt-8 rounded-3xl bg-yehi-navy p-7 text-white"><Mail className="h-6 w-6 text-or-light"/><h3 className="mt-5 text-2xl text-white">Aucune offre ouverte ?</h3><p className="mt-3 text-sm leading-6 text-white/65">Envoyez-nous votre profil et expliquez comment vous aimeriez contribuer.</p><a href="mailto:contact@yehiortech.com?subject=Candidature%20spontanée" className="mt-6 inline-block"><Button variant="gold">Envoyer ma candidature <ArrowRight className="h-4 w-4"/></Button></a></div></div></section><Footer/></main> }
