import Link from "next/link";
import { ArrowRight, Compass, Lightbulb, ShieldCheck, Sparkles, Target } from "lucide-react";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import PageHero from "@/components/ui/PageHero";
import { Button } from "@/components/ui/Button";

const values = [{ icon: Lightbulb, title: "Clarté", text: "Nous transformons les sujets complexes en décisions compréhensibles." }, { icon: Target, title: "Impact", text: "Chaque choix de design et de technologie doit servir un résultat concret." }, { icon: ShieldCheck, title: "Fiabilité", text: "Nous avançons avec des étapes visibles, des délais clairs et des bases solides." }, { icon: Compass, title: "Proximité", text: "Une expertise internationale, pensée pour les réalités du Bénin et de l’Afrique." }];

export default function AboutPage(){return <main className="min-h-screen bg-white"><Navbar /><PageHero eyebrow="À propos de YEHI OR" title="Faire de la technologie un levier de clarté." description="YEHI OR signifie « que la lumière soit ». Notre mission est de donner cette clarté aux marques, produits et opérations que nous accompagnons." image="/images/heroes/about.png" cta="Découvrir notre méthode" /><section className="site-container section-padding grid gap-16 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Notre histoire</p><h2 className="mt-5 text-noir-profond">Une agence née à <span className="text-gradient-blue">Parakou.</span></h2></div><div className="space-y-6 text-lg leading-8 text-gris"><p>YEHI OR Tech accompagne les entrepreneurs, PME, écoles et organisations qui veulent passer d’une présence numérique dispersée à un système plus crédible et plus utile.</p><p>Nous réunissons stratégie, design, développement et intelligence artificielle dans un même accompagnement. Pas pour ajouter de la technologie, mais pour résoudre les bons problèmes avec méthode.</p><div className="rounded-3xl bg-bleu-soft p-7 text-noir-profond"><Sparkles className="h-7 w-7 text-or" /><p className="mt-4 text-2xl font-semibold leading-9">Construire des expériences digitales qui donnent confiance avant même le premier échange.</p></div></div></section><section className="bg-slate-50 py-24 md:py-32"><div className="site-container"><div className="mb-12 max-w-xl"><p className="eyebrow">Nos principes</p><h2 className="mt-5 text-noir-profond">La lumière comme <span className="text-gradient-blue">standard.</span></h2></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{values.map(({icon:Icon,title,text})=><article key={title} className="rounded-3xl border border-slate-200 bg-white p-7"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-bleu-soft text-bleu-tech"><Icon className="h-6 w-6" /></span><h3 className="mt-8 text-2xl text-noir-profond">{title}</h3><p className="mt-3 text-sm leading-6 text-gris">{text}</p></article>)}</div></div></section><section className="bg-yehi-navy py-20 text-center text-white"><div className="site-container"><h2 className="text-white">Prêt à éclaircir votre prochain projet ?</h2><Link href="/devis" className="mt-8 inline-block"><Button variant="gold">Échanger avec nous <ArrowRight className="h-4 w-4" /></Button></Link></div></section><Footer /></main>}
