"use client";

import { useMemo, useState } from "react";
import { Activity, ArrowDownRight, ArrowUpRight, BookOpen, CircleDollarSign, ClipboardList, CloudOff, LayoutDashboard, LogOut, Plus, Settings2, ShoppingBag, Users, WalletCards } from "lucide-react";
import { addManagerEvent } from "@/lib/manager-local-store";

type Props = { session: { email: string; name?: string; provider: string } };
const nav = [
  ["Vue d'ensemble", LayoutDashboard], ["Clients & CRM", Users], ["Ventes", ShoppingBag], ["Prestations", ClipboardList], ["Caisse", CircleDollarSign], ["Trésorerie", WalletCards], ["Academia", BookOpen], ["Rapports", Activity],
] as const;

export default function ManagerDashboard({ session }: Props) {
  const [active, setActive] = useState("Vue d'ensemble");
  const [notice, setNotice] = useState("Mode connecté · synchronisation prête");
  const [showQuick, setShowQuick] = useState(false);
  const [amount, setAmount] = useState("");
  const [label, setLabel] = useState("");
  const [center, setCenter] = useState<"BOUTIQUE" | "ACADEMIA" | "DESIGN" | "TEXTILE" | "DEV">("BOUTIQUE");
  const initials = useMemo(() => (session.name || session.email).slice(0, 2).toUpperCase(), [session]);

  async function quickSale() {
    const value = Number(amount);
    if (!value || !label) return;
    await addManagerEvent({ type: "sale", amount: value, label, center });
    setAmount(""); setLabel(""); setShowQuick(false); setNotice("Vente enregistrée sur cet appareil · en attente de synchronisation");
  }

  return (
    <main className="min-h-screen bg-[#f6f8fc] text-[#08152f]">
      <aside className="fixed inset-y-0 left-0 hidden w-72 border-r border-slate-200 bg-[#071b48] px-5 py-6 text-white lg:block">
        <div className="flex items-center gap-3 px-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-or font-bold text-yehi-navy">YO</div><div><p className="font-semibold">YEHI OR</p><p className="text-[10px] uppercase tracking-[.2em] text-white/50">Manager</p></div></div>
        <div className="mt-12 grid gap-1">{nav.map(([name, Icon]) => <button key={name} onClick={() => setActive(name)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition ${active === name ? "bg-white/15 text-or-light" : "text-white/65 hover:bg-white/10 hover:text-white"}`}><Icon className="h-4 w-4" />{name}</button>)}</div>
        <div className="absolute inset-x-5 bottom-6 rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs font-semibold">Academia en production</p><p className="mt-2 text-xs leading-5 text-white/55">Suivez les abonnements, le support et les revenus récurrents dans un espace dédié.</p></div>
      </aside>
      <section className="lg:ml-72">
        <header className="sticky top-0 z-20 flex items-center justify-between border-b border-slate-200 bg-white/90 px-5 py-4 backdrop-blur-xl sm:px-8"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-bleu-tech">{active}</p><p className="mt-1 text-sm text-slate-500">Mardi 22 septembre 2026 · Parakou</p></div><div className="flex items-center gap-3"><span className="hidden items-center gap-2 rounded-full bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700 sm:flex"><span className="h-2 w-2 rounded-full bg-emerald-500" /> En ligne</span><div className="flex h-10 w-10 items-center justify-center rounded-full bg-bleu-soft text-xs font-bold text-bleu-tech">{initials}</div><form action="/api/manager/logout" method="post"><button aria-label="Se déconnecter" className="rounded-xl p-2 text-slate-400 transition hover:bg-slate-100 hover:text-red-600"><LogOut className="h-4 w-4" /></button></form></div></header>
        <div className="px-5 py-7 sm:px-8 sm:py-10"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Pilotage d'entreprise</p><h1 className="mt-4 text-4xl sm:text-5xl">Bonjour, {session.name?.split(" ")[0] || "dirigeant"}.</h1><p className="mt-3 max-w-xl text-slate-500">Une vue claire sur la boutique, la trésorerie et le produit Academia.</p></div><button onClick={() => setShowQuick(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-bleu-tech px-5 py-3 text-sm font-bold text-white shadow-lg shadow-bleu-tech/20 transition hover:bg-yehi-navy"><Plus className="h-4 w-4" /> Nouvelle vente</button></div>
          <div className="mb-6 flex items-center gap-2 rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-xs text-blue-800"><CloudOff className="h-4 w-4" /> {notice}</div>
          <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{([["Recettes du mois", "485 000 F", "+18,4 %", ArrowUpRight, "text-emerald-600"], ["Dépenses du mois", "196 500 F", "Sous contrôle", ArrowDownRight, "text-orange-600"], ["Solde disponible", "288 500 F", "3 enveloppes actives", WalletCards, "text-bleu-tech"], ["Academia MRR", "200 000 F", "6 établissements", BookOpen, "text-or"]] as const).map(([label, value, delta, Icon, tone]) => <article key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[.14em] text-slate-400">{label}</p><Icon className={`h-5 w-5 ${tone}`} /></div><p className="mt-6 text-3xl font-bold tracking-tight">{value}</p><p className={`mt-2 text-xs font-semibold ${tone}`}>{delta}</p></article>)}</div>
          <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.8fr]"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-lg font-bold">Flux de trésorerie</p><p className="mt-1 text-sm text-slate-500">Vue simplifiée des six dernières semaines</p></div><button className="rounded-lg p-2 text-slate-400 hover:bg-slate-50"><Settings2 className="h-4 w-4" /></button></div><div className="mt-8 grid h-48 grid-cols-6 items-end gap-3">{[42, 58, 45, 74, 63, 88].map((height, index) => <div key={index} className="flex h-full flex-col items-center justify-end gap-2"><div className="w-full max-w-12 rounded-t-lg bg-gradient-to-t from-bleu-tech to-or" style={{ height: `${height}%` }} /><span className="text-[10px] text-slate-400">S{index + 1}</span></div>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-lg font-bold">Raccourcis métier</p><div className="mt-5 grid gap-3">{([["Ajouter une dépense", "Garder chaque sortie justifiée", CircleDollarSign], ["Créer une commande", "Acompte et délai visibles", ClipboardList], ["Suivre Academia", "Renouvellements et support", BookOpen]] as const).map(([title, text, Icon]) => <button key={String(title)} onClick={() => setActive(String(title))} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3 text-left transition hover:border-bleu-tech hover:bg-bleu-soft"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-slate-100 text-bleu-tech"><Icon className="h-4 w-4" /></span><span><span className="block text-sm font-semibold">{title}</span><span className="mt-1 block text-xs text-slate-500">{text}</span></span></button>)}</div></section></div>
          <div className="mt-6 grid gap-6 lg:grid-cols-3"><article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-bold">Enveloppes de trésorerie</p><div className="mt-5 grid gap-4">{[["Charges fixes", "80 000 F", "bg-bleu-tech"], ["Fonds Academia", "45 000 F", "bg-or"], ["Maintenance", "30 000 F", "bg-emerald-500"]].map(([name, value, color]) => <div key={String(name)}><div className="flex justify-between text-xs"><span className="font-semibold">{name}</span><span className="text-slate-500">{value}</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className={`h-2 w-2/3 rounded-full ${color}`} /></div></div>)}</div></article><article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-bold">Commandes en cours</p><div className="mt-5 grid gap-3">{[["Dossier scolaire", "Aujourd'hui", "En production"], ["T-shirts promotion", "Demain", "Acompte reçu"], ["Affiche événement", "Jeudi", "À valider"]].map(([name, date, status]) => <div key={String(name)} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div><p className="text-sm font-semibold">{name}</p><p className="mt-1 text-xs text-slate-500">{date}</p></div><span className="rounded-full bg-white px-2 py-1 text-[10px] font-bold text-bleu-tech">{status}</span></div>)}</div></article><article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-bold">Academia à suivre</p><div className="mt-5 grid gap-3">{[["Collège Lumière", "Renouvellement dans 5 j"], ["École Les Pionniers", "2 tickets ouverts"], ["Complexe Horizon", "Démonstration à planifier"]].map(([name, text]) => <div key={String(name)} className="flex gap-3 rounded-xl border border-slate-100 p-3"><span className="mt-1 h-2 w-2 rounded-full bg-or" /><div><p className="text-sm font-semibold">{name}</p><p className="mt-1 text-xs text-slate-500">{text}</p></div></div>)}</div></article></div>
        </div>
      </section>
      {showQuick && <div className="fixed inset-0 z-50 grid place-items-center bg-yehi-navy/50 p-5"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="eyebrow">Enregistrement local</p><h2 className="mt-3 text-3xl">Nouvelle vente</h2></div><button onClick={() => setShowQuick(false)} className="text-slate-400">×</button></div><div className="mt-6 grid gap-4"><input value={label} onChange={(e) => setLabel(e.target.value)} placeholder="Ex. 50 photocopies A4" className="form-input" /><input value={amount} onChange={(e) => setAmount(e.target.value)} type="number" min="0" placeholder="Montant en F CFA" className="form-input" /><select value={center} onChange={(e) => setCenter(e.target.value as typeof center)} className="form-input"><option value="BOUTIQUE">Boutique</option><option value="ACADEMIA">Academia</option><option value="DESIGN">Design</option><option value="TEXTILE">Textile</option><option value="DEV">Développement</option></select><button onClick={quickSale} className="rounded-xl bg-bleu-tech px-5 py-3 font-bold text-white">Enregistrer hors connexion</button></div></div></div>}
    </main>
  );
}
