import Link from "next/link";
import { ArrowLeft, ArrowRight, Clock3 } from "lucide-react";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import PageHero from "@/components/ui/PageHero";
const articles=[{slug:"presence-digitale-professionnelle",title:"Pourquoi une présence digitale crédible commence par la clarté",category:"Stratégie",time:"6 min",intro:"Une présence digitale utile ne cherche pas à tout dire. Elle aide la bonne personne à comprendre, croire et agir."},{slug:"automatiser-experience-client",title:"Automatiser sans déshumaniser son expérience client",category:"IA & opérations",time:"8 min",intro:"L’automatisation est efficace lorsqu’elle retire de la friction sans retirer l’attention humaine."},{slug:"site-qui-convertit",title:"Les fondations d’un site qui transforme les visites en demandes",category:"Web & conversion",time:"5 min",intro:"Un site professionnel est une architecture de confiance avant d’être une collection de pages."}];
export function generateStaticParams(){return articles.map(article=>({slug:article.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const article=articles.find(item=>item.slug===slug);return{title:article?.title??"Article",description:article?.intro};}
export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const article=articles.find(item=>item.slug===slug);if(!article)return null;return <main className="min-h-screen bg-white"><Navbar/><PageHero eyebrow={`Journal · ${article.category}`} title={article.title} description={article.intro} image="/images/heroes/home.png" cta="Parler à l’équipe"/><article className="site-container max-w-3xl section-padding"><div className="flex items-center gap-2 text-xs text-gris"><Clock3 className="h-4 w-4"/>{article.time} de lecture</div><div className="prose prose-slate mt-10 max-w-none"><p>Les entreprises qui avancent le mieux ne commencent pas par empiler des outils. Elles commencent par clarifier l’expérience qu’elles veulent offrir et le problème qu’elles veulent résoudre.</p><h2>Commencer par le contexte</h2><p>Votre activité, vos clients et vos contraintes sont le point de départ. Une solution digitale pertinente doit être accessible, rassurante et adaptée à vos usages réels.</p><h2>Transformer la clarté en système</h2><p>Le design, le contenu, la technologie et les automatisations doivent ensuite travailler ensemble. C’est ce qui permet de gagner en visibilité, en crédibilité et en efficacité.</p><blockquote>Une bonne solution numérique rend une décision plus simple.</blockquote></div><Link href="/blog" className="mt-12 inline-flex items-center gap-2 text-sm font-bold text-bleu-tech"><ArrowLeft className="h-4 w-4"/>Retour au journal <ArrowRight className="h-4 w-4"/></Link></article><Footer/></main>}
