import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import PageHero from "@/components/ui/PageHero";
import { Button } from "@/components/ui/Button";
import { packs } from "@/data/packs";

export default function PacksPage(){return <main className="min-h-screen bg-slate-50"><Navbar/><PageHero eyebrow="Offres & packs" title="Des solutions lisibles pour chaque étape." description="Des offres structurées pour renforcer votre crédibilité, lancer votre présence digitale ou automatiser un processus métier." image="/images/heroes/tarifs.png"/><section className="site-container section-padding"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{packs.map(pack=><article key={pack.slug} className={`relative rounded-[2rem] p-7 transition duration-300 hover:-translate-y-2 ${pack.highlighted?"bg-bleu-tech text-white shadow-[0_22px_70px_rgba(11,79,211,.26)]":"border border-slate-200 bg-white"}`}><div className="flex items-center justify-between"><span className={`rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-[.15em] ${pack.highlighted?"bg-or-light text-noir-profond":"bg-bleu-soft text-bleu-tech"}`}>{pack.category}</span>{pack.highlighted&&<span className="rounded-full bg-or-light px-3 py-1 text-[10px] font-bold uppercase tracking-[.12em] text-noir-profond">Recommandé</span>}</div><h2 className={`mt-8 text-3xl ${pack.highlighted?"text-white":"text-noir-profond"}`}>{pack.name}</h2><p className={`mt-3 min-h-14 text-sm leading-6 ${pack.highlighted?"text-white/70":"text-gris"}`}>{pack.description}</p><p className={`mt-7 text-3xl font-bold ${pack.highlighted?"text-or-light":"text-bleu-tech"}`}>{pack.price}</p><ul className="mt-7 space-y-3 border-t border-current/10 pt-6">{pack.features.map(feature=><li key={feature} className="flex gap-3 text-sm"><Check className={`h-5 w-5 shrink-0 ${pack.highlighted?"text-or-light":"text-bleu-tech"}`}/>{feature}</li>)}</ul><Link href={`/devis?pack=${pack.slug}`} className="mt-8 inline-block"><Button variant={pack.highlighted?"gold":"primary"}>Choisir cette offre <ArrowRight className="h-4 w-4"/></Button></Link></article>)}</div></section><section className="bg-yehi-navy py-20 text-center text-white"><div className="site-container"><h2 className="text-white">Besoin d’une offre sur mesure ?</h2><p className="mx-auto mt-5 max-w-xl text-white/65">Contactez-nous : nous établissons un devis adapté à votre budget et à vos objectifs.</p><Link href="/devis" className="mt-8 inline-block"><Button variant="gold">Demander un devis personnalisé</Button></Link></div></section><Footer/></main>}
