import Link from "next/link";
import { ArrowLeft, ArrowRight, Check } from "lucide-react";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import PageHero from "@/components/ui/PageHero";
import { Button } from "@/components/ui/Button";
import { projects } from "@/data/portfolio";

export function generateStaticParams() { return projects.map(project => ({ slug: project.id })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const project = projects.find(item => item.id === slug); return { title: project?.title ?? "Réalisation", description: project?.description }; }
export default async function PortfolioDetailPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const project = projects.find(item => item.id === slug); if (!project) return null; return <main className="min-h-screen bg-slate-50"><Navbar/><PageHero eyebrow={`Réalisation · ${project.category}`} title={project.title} description={project.description} image={project.thumbnail ?? "/images/heroes/portfolio.png"} cta="Parler d’un projet similaire"/><section className="site-container section-padding grid gap-10 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[2rem] bg-white p-8 shadow-[0_16px_50px_rgba(7,27,72,.08)]"><p className="eyebrow">Étude de cas</p><h2 className="mt-5 text-noir-profond">Une expérience pensée pour <span className="text-gradient-blue">servir un objectif.</span></h2><p className="mt-6 text-lg leading-8 text-gris">Cette réalisation illustre notre manière de réunir design, technologie et clarté produit. Les détails de périmètre sont disponibles sur demande.</p><div className="mt-8 flex flex-wrap gap-2">{project.tags.map(tag=><span key={tag} className="rounded-full bg-bleu-soft px-3 py-1 text-xs font-bold text-bleu-tech">{tag}</span>)}</div></div><div className="rounded-[2rem] bg-yehi-navy p-8 text-white"><p className="eyebrow text-or-light">Stack & statut</p><ul className="mt-7 space-y-4">{project.tech.map(item=><li key={item} className="flex gap-3 text-sm text-white/75"><Check className="h-5 w-5 text-or-light"/>{item}</li>)}</ul><p className="mt-8 border-t border-white/15 pt-5 text-sm text-white/60">Statut : {project.status === "live" ? "Actif" : project.status === "development" ? "En développement" : "Concept"}</p><Link href="/devis" className="mt-8 inline-block"><Button variant="gold">Créer le vôtre <ArrowRight className="h-4 w-4"/></Button></Link></div></section><div className="site-container pb-20"><Link href="/portfolio" className="inline-flex items-center gap-2 text-sm font-bold text-bleu-tech"><ArrowLeft className="h-4 w-4"/>Retour aux réalisations</Link></div><Footer/></main> }
